services:
  airflow-init:
    image: apache/airflow:2.10.4
    container_name: airflow_init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/airflow
    entrypoint: >
      bash -c "airflow db init && airflow users create --username admin --password admin --role Admin --firstname Admin --lastname Admin --email admin@example.com || true"
    volumes:
      - ./airflow:/opt/airflow

  airflow-webserver:
    image: apache/airflow:2.10.4
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/airflow
      AIRFLOW__WEBSERVER__RBAC: "True"
    command: ["airflow", "webserver"]
    volumes:
      - ./airflow:/opt/airflow

  airflow-scheduler:
    image: apache/airflow:2.10.4
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/airflow
    command: ["airflow", "scheduler"]
    volumes:
      - ./airflow:/opt/airflow